### PR TITLE
correction czech translat

### PR DESCRIPTION
**Pull request by LLZN**
character correction :  \n   and    \n\n

Please do not remove these characters. The button will show the method of action in the top line and the name of the action in the bottom line. Thank you.
You removed these characters from the previous translation and did not add a space character: \ u0020, so the text of the two words was without a space.

I still have a question, could I translate the terms below (AA Phenotype Patcher):
Choose app for whitelist = Vyberte aplikaci do seznamu oblíbených
Added : = Přidáno :
Removed := Odstraněno :
cancel / Cancel = Zrušit
Failed to access cancel method by reflection = Chyba přístupu zrušila způsob zrcadlení
Failed to invoke cancel method by reflection = Chyba použití zrušila způsob zrcadlení
Reboot phone now? = Chcete restartovat telefon nyní?
Rebooting... = Restartování...
reboot now = Restartovat nyní
Do you want to revert everything? Please manually restart the app after doing so. = Chcete obnovit vše? Po ukončení činnosti manuálně restartujte aplikaci.
Root access denied. Please allow root access. = Přístup k ROOT byl odepřen. Povolte přístup k ROOT.
ok = OK
V.2.4 = Verze 2.4

### CODE REVIEW

**Comment by shmykelsa** [comment]
Please don't use line characters or multiple line characters when they are not necessary. The original app is designed to have buttons like

"Activate x"
and not 
"Activate
X"

Therefore translations should not have new lines.

**Comment by shmykelsa** [comment]
Also, please consider joining translations on Crowdin https://crowdin.com/project/aa-aio-tweaker

New strings to be translated are usually out on Crowdin before the repo.

**Comment by LLZN** [comment]
2 lines will fit on the buttons without any problems and in my opinion it
is clearer.

For the Legend status item, there are 2 free lines so that the up and down
buttons do not jump when the text changes, ie so that the number of lines
is the same for both different texts.

I would like you to leave 2 lines for the Czech translation.  If there was
a problem with that (user feedback), I would adjust it to the original
characters.  You did not remove the new characters for some items from the
previous translation.

Thank you L.


Dne ne 17. 1. 2021 11:02 uživatel Gabriele Rizzo <notifications@github.com>
napsal:

**Comment by shmykelsa** [comment]
The buttons jumping is probably due to a very big size for the text. I've increased the number of minimum lines on the layout so that most of the screen dimensions will not have such problem. 
In most of the submitted translations there were unnecessary double new lines. And all of them were refactored to just a new line. Two new lines do not fit AA AIO TWEAKER needs.
If you have any issues on features please refrain from submitting translations that change the design, but use issues instead. 
The scope of translations are just to translate the app. 
Thanks.

**Comment by LLZN** [comment]
I understand, I will correct the line bounce to the original values ​​and I
will submit a new translation for approval.  Delete the existing
translation change request.

Regards L.

Dne ne 17. 1. 2021 11:40 uživatel Gabriele Rizzo <notifications@github.com>
napsal:

**Comment by LLZN** [comment]
Dne ne 17. 1. 2021 11:55 uživatel Loun Ladislav <lounovi@gmail.com> napsal:

**Pull request closed without merging**
